import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "CinePulse AI | Automated Entertainment News",
  description: "Fully automated Bollywood and Hollywood news, generated by AI.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-950 text-slate-100 min-h-screen flex flex-col`}
      >
        <header className="border-b border-white/10 p-6">
           <h1 className="text-2xl font-black uppercase tracking-wider text-orange-500">CinePulse AI</h1>
        </header>
        <main className="flex-1 p-8">
           {children}
        </main>
        <footer className="border-t border-white/10 p-6 text-center text-sm text-slate-500">
          © {new Date().getFullYear()} CinePulse AI. Fully Automated Platform.
        </footer>
      </body>
    </html>
  );
}
